services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: salaryfits
    container_name: salaryfits-dev-app
    ports:
      - '3000:3000'
      - '3036:3036'
      - '3037:3037'
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle:delegated
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine 
    container_name: postgres_db
    restart: on-failure
    volumes:
      - postgres_rails_data:/var/lib/postgresql/data:delegated
    env_file: .env
    environment:
      - POSTGRES_USER=${SALARYFITS_DATABASE_USER}
      - POSTGRES_PASSWORD=${SALARYFITS_DATABASE_PASSWORD}

volumes:
  bundle:
  postgres_rails_data:
